#pragma kernel CSMain

struct Vert2 
{
    float4 v1;
    float4 v2;
}

float surface;

RWStructuredBuffer<float3> Result;
RWStructuredBuffer<Vert2> Input;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    Result[id.x] = interpolateVerts(Input[id.x].v1, Input[id.x].v2);
}

float3 interpolateVerts(float4 v1, float4 v2) {
    float t = (surface - v1.w) / (v2.w - v1.w);
    return v1.xyz + t * (v2.xyz - v1.xyz);
}
